---
 homebrew_cask_packages:
  - 1password
  - alfred
  - bartender
  - caffeine
  - dash
  - dropbox
  - google-chrome
  - hammerspoon
  - flux
  - iterm2
  - intellij-idea
  - karabiner
  - virtualbox
  - vagrant
  - rescuetime
  - sourcetree
  - slack
  - spotify
  - vlc
  - java
  - the-unarchiver
